version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.PublicSuffix.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: FYQvxOzWs+SMxuE85dk3Blvdi+qv9pGtr9hgPhToslRDPxn6cuME/Gbl6t+E48QU
  artifact: /.*\.nupkg/